services:
  app:
    build: .
    ports:
      - 3000:3000
    env_file:
      - container.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - container.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  backup:
    image: ghcr.io/realorangeone/db-auto-backup:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/c/Users/strah/OneDrive/Documents/vila-spliit:/var/backups
    environment:
      - SUCCESS_HOOK_URL=https://hc-ping.com/350ead85-5cda-431a-88ca-fb58cd224f30
      - INCLUDE_LOGS=true
